version: 2

env:
  - GO111MODULE=on
  - GOPROXY="https://proxy.golang.org,direct"

archives:
  - id: default

builds:
  - binary: wtfutil
    goos:
      - linux
    goarch:
      - arm64

before:
  hooks:
    - make install

announce:
  discourse:
    enabled: true
    server: "https://discuss.linodians.com"
